## Project #1, Lab 3 - Creating and Applying Conditional variables, Sorting values, Handling Dates

Make sure to load necessary packages and your datasets first!

In [1]:
import pandas as pd

In [2]:
## Load data
air_data = pd.read_csv('AirQuality_Daily_StudentVersion.csv')

## Turn data into a dataframe

air_data = pd.DataFrame(air_data)
## View data
print(air_data)

          date  monitor_index   humidity    pressure  temperature         voc  \
0     02/23/24         195089  14.377667  912.884333    62.266667   51.998667
1     02/23/24         195365  12.223600  926.403000    71.193400   64.920800
2     02/23/24         195541  20.095750  905.670750    61.008250   68.307000
3     02/24/24         195089  25.368000  911.708833    51.462458   91.176750
4     02/24/24         195365  23.703083  925.282125    56.818208  107.863708
...        ...            ...        ...         ...          ...         ...
8296  03/24/25         195373  23.636208  915.998292    61.489083  421.493750
8297  03/24/25         195379  28.043545  954.294546    66.009182  301.074800
8298  03/24/25         195383  31.451375  936.556583    55.752792  353.478000
8299  03/24/25         195385        NaN         NaN          NaN         NaN
8300  03/24/25         195541  20.494500  901.484750    61.222167  485.556417

      analog_input  pm2.5_alt  pm1.0_atm  pm2.5_atm  pm10.0_atm  \
0         0.051333   0.100000   0.000000   0.002500    0.039667
1         0.000000   0.180000   0.004800   0.020000    0.176000
2         0.020000   0.162500   0.004125   0.014812    0.063937
3         0.052667   0.437500   0.099542   0.170667    0.355208
4         0.000000   0.475000   0.099208   0.231687    0.548583
...            ...        ...        ...        ...         ...
8296      0.020000   0.762500   0.486583   0.830021    1.416125
8297      0.000000   0.800000   5.625545   5.873364    6.056773
8298      0.050000   0.575000   0.267500   0.478375    0.818146
8299      0.010000   0.970833   0.739500   1.088604    1.340563
8300      0.020000   0.554167   0.132083   0.340417    0.737375

      sensor.latitude  sensor.longitude  sensor.altitude  \
0           40.050922       -101.533570             3005
1           40.200330       -100.639885             2576
2           41.128284       -101.720220             3220
3           40.050922       -101.533570             3005
4           40.200330       -100.639885             2576
...               ...               ...              ...
8296        41.148170       -100.761800             2800
8297        40.877007        -97.579445             1639
8298        41.779380        -99.138040             2174
8299        40.019714        -98.071840             1597
8300        41.128284       -101.720220             3220

                                            sensor.name
0                                      Swnphd-Benklemen
1                                         Swnphd-mccook
2                                       Swnphd-ogallala
3                                      Swnphd-Benklemen
4                                         Swnphd-mccook
...                                                 ...
8296                                WCDHD City Building
8297                                           FCHD-YPS
8298                Loup Basin Public Health Department
8299  South Heartland District Health Dept. Superior...
8300                                    Swnphd-ogallala

[8301 rows x 15 columns]

### Creating Categories

One thing we may want to do with our code is to create categories based on a variable. For example, our temperature data in this data set is numerical, but the UNMC Group has defined temperature categories. We may want to create a new column that "looks" at the temperature column and then assigns a category to each temperature in a new column.  Every function starts with `def`.  Then the blue text after `def` is the name of your function.  Your function takes `arguments`, variables that can be inputed to the function. Don't forget to put `:` after your arguments so that Python knows to indent!  Then we use a series of `elif` statements to define what happens to the variable when it is put into the function.

In [3]:
### Sample temperature function
#goal: assign temp labels based on numerical data

def assign_temperature(X):
    if X < 32:
        return 'Bellow Freezing'
    elif 32 <= X <= 50:
        return 'Cool'
    elif 51 < X <= 70:
        return 'Warm'
    else:
        return 'Hot'

Now that we have the function, we need to `apply` that function to our data. If we have a created a function, it doesn't mean this function has been used yet, its just defined in what we call the 'global environment'.  To make sure our function is applied to our data our steps are as follows:
1. Make sure we `apply` the function to the column we want to be manipulated
2. Assign the new column we create to a column name inside our original dataset

In [4]:
## Apply your function to the temperature column in your air_data

air_data['temperature_level'] = air_data['temperature'].apply(assign_temperature)

air_data.head(5)

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,temperature_level
0,02/23/24,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.1000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen,Warm
1,02/23/24,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.1800,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook,Hot
2,02/23/24,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.1625,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala,Warm
3,02/24/24,195089,25.368000,911.708833,51.462458,91.176750,0.052667,0.4375,0.099542,0.170667,0.355208,40.050922,-101.533570,3005,Swnphd-Benklemen,Warm
4,02/24/24,195365,23.703083,925.282125,56.818208,107.863708,0.000000,0.4750,0.099208,0.231687,0.548583,40.200330,-100.639885,2576,Swnphd-mccook,Warm

#### Lab Activity #1: Create a function for altitude levels
Create a function that assigns three different levels to altitude: Low, Medium and High.  You can choose what values to set as your conditions in this function.

In [5]:
### Enter your response to Lab Activity #1 in the space below:

def assign_altitude(X):
    if X < 1000:
        return 'Low'
    elif 1000 <= X <= 2000:
        return 'Medium'
    else:
        return 'High'

air_data['altitude_level'] = air_data['sensor.altitude'].apply(assign_altitude)

air_data.head(5)

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,temperature_level,altitude_level
0,02/23/24,195089,14.377667,912.884333,62.266667,51.998667,0.051333,0.1000,0.000000,0.002500,0.039667,40.050922,-101.533570,3005,Swnphd-Benklemen,Warm,High
1,02/23/24,195365,12.223600,926.403000,71.193400,64.920800,0.000000,0.1800,0.004800,0.020000,0.176000,40.200330,-100.639885,2576,Swnphd-mccook,Hot,High
2,02/23/24,195541,20.095750,905.670750,61.008250,68.307000,0.020000,0.1625,0.004125,0.014812,0.063937,41.128284,-101.720220,3220,Swnphd-ogallala,Warm,High
3,02/24/24,195089,25.368000,911.708833,51.462458,91.176750,0.052667,0.4375,0.099542,0.170667,0.355208,40.050922,-101.533570,3005,Swnphd-Benklemen,Warm,High
4,02/24/24,195365,23.703083,925.282125,56.818208,107.863708,0.000000,0.4750,0.099208,0.231687,0.548583,40.200330,-100.639885,2576,Swnphd-mccook,Warm,High

### Sorting our data

Let's start by reminding ourselves how to aggregate data.  Let's calculate the max, min, mean, and median of the `pm_2.5` values and name this new data set something besides `air_data`

In [6]:
## Group your data

air_data_pm25 = air_data.groupby(['sensor.name']).agg(max = ('pm2.5_atm', 'max'),
                                                     min = ('pm2.5_atm','min'), 
                                                     mean = ('pm2.5_atm','mean'), 
                                                     median = ('pm2.5_atm','median'))

### Aggregate the grouped data

### Make sure the students take the mean, median and max of the values of the columns.  
## Summary stats on PM 2.5

Now that we have the aggregated data, let's sort our values to find the top 5 highest means by location.  We create a new dataframe and append the `sort_values()` function, giving it a specific set of arguments to let `.sort_values()` know what to sort `by` and if the order is `ascending` or `descending`.

In [7]:
### Find the top 5 locations with highest mean and median values of each parameter

### PM 2.5 Mean

top5_pm25 = air_data_pm25.sort_values(by = 'mean', ascending = False)
top5_pm25.head(5)

## Here is a link to how this code was generated: https://chatgpt.com/share/695e9143-2c74-8000-bed2-06b976fb8e95

,max,min,mean,median
sensor.name,,,,
Broken Bow,3205.868854,0.019187,928.710593,36.050240
#16 - Richardson County Courthouse,3782.823313,0.243729,700.127342,11.977344
#18 - Southeast District Health Department- Tecumseh,2987.467563,0.140708,613.175352,10.322875
NCDHD O'Neill #11,2078.873729,0.136958,164.495078,7.251208
Swnphd-mccook,3053.114292,0.020000,123.011622,4.582281

#### Lab Activity #2: VOC summary
Create an aggregated summary of vocs by the max value.  Print out the first 10 rows of the data set grouped by monitor_index

In [8]:
### Enter your response to Lab Activity #2 in the space below

air_data_monitor = air_data.groupby(['monitor_index']).agg(max = ('voc', 'max'))

monitor_index10 = air_data_monitor.sort_values(by = 'max', ascending = False)
monitor_index10.head(10)

                       max
monitor_index
195541         1209.931571
194969         1135.473000
195343          884.649000
195379          856.012625
195365          849.734917
195333          842.127417
195327          810.410375
195089          788.161667
195383          780.413792
195345          779.814056

#### Sorting by Dates
Dates can sometimes be difficult to wrangle in Python.  Luckily the AirPurple dataset is a 'clean' dataset which has dates formatted as mm/dd/yy which Python easily recognizes once the `air_data` is in a dataframe.  Let's use `.sort_values()` as above to sort by date.  First we will select only three columns: `date`, `sensor.name` and `voc`.  Then sort by date.

In [9]:
### Apply filters

unhealthy_voc = air_data[ air_data['voc'] >= 25]
## Sort values by date

unhealthy_dates = unhealthy_voc.sort_values('date')

unhealthy_dates

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name,temperature_level,altitude_level
6552,01/01/25,194969,36.147375,907.732292,38.693125,377.393125,0.020000,1.412500,1.371146,2.059771,2.335875,40.512820,-101.629420,3269,SWNPHD-Imerial,Cool,High
6571,01/01/25,195541,36.970833,908.868458,36.860917,522.399333,0.020000,3.516667,4.182646,5.777708,6.395833,41.128284,-101.720220,3220,Swnphd-ogallala,Cool,High
6570,01/01/25,195385,37.722167,968.707250,41.155667,199.845625,0.010000,1.991667,2.347771,3.132188,3.286229,40.019714,-98.071840,1597,South Heartland District Health Dept. Superior...,Cool,Medium
6569,01/01/25,195383,43.241458,946.005042,35.972208,193.350875,0.050042,2.325000,2.838042,4.283229,5.058354,41.779380,-99.138040,2174,Loup Basin Public Health Department,Cool,High
6568,01/01/25,195379,43.332500,966.248125,39.498667,232.136042,0.000000,1.745833,1.719875,2.979125,3.684375,40.877007,-97.579445,1639,FCHD-YPS,Cool,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6532,12/31/24,194969,47.771083,905.014333,38.990250,300.181458,0.020000,1.608333,2.290146,2.964042,3.137938,40.512820,-101.629420,3269,SWNPHD-Imerial,Cool,High
6549,12/31/24,195383,59.430625,941.595875,34.322375,145.707458,0.050083,1.770833,2.369958,3.671896,4.557833,41.779380,-99.138040,2174,Loup Basin Public Health Department,Cool,High
6550,12/31/24,195385,51.009708,960.688750,41.530458,115.970583,0.010000,3.483333,4.563604,6.065021,6.260521,40.019714,-98.071840,1597,South Heartland District Health Dept. Superior...,Cool,Medium
6540,12/31/24,195339,60.048542,977.422417,41.088125,247.865667,0.000000,5.704167,6.823188,10.265104,11.270750,40.676200,-95.858300,1055,#17 - Otoe County,Cool,Medium
6548,12/31/24,195379,54.083458,958.772375,40.486750,210.853833,0.000000,1.987500,2.207271,3.963729,5.235542,40.877007,-97.579445,1639,FCHD-YPS,Cool,Medium

### Calculating Mode
The mode is most appropriate for categorical variables or values that repeat exactly.Continuous measurements such as VOC or PM concentrations are better summarized using mean, median, or maximum values. But we can calculate mode for their categories. In this example, we are categorizing the `pm2.5_atm` values and using the categories to calculate mode for each `monitor_index`. 

We do not necessarily expect large differences in PM2.5 across locations. This analysis helps us identify whether different typical air-quality conditions are experienced or whether conditions are broadly similar across the network.

In [ ]:
# Defining a function for categorizing pm2.5_atm


# Applying this function to the dataset

In [ ]:
# grouping by monitor index


# finding the pm2.5_atm category mode

#### Lab Activity #3: Combine Lab 2 and Lab 3
Let's combine everything we've learned about organizing data so far.  In the space below, write code that meets the following requests:
1. Filters for only Warm temperatures
2. Presents the median of the voc concentration
3. Groups the data by sensor altitude
4. Shows only the top 3 rows of data with sensor altitude

In [10]:
### Enter your response to the Lab #3 Activity in the space below

warm_air = air_data[air_data['temperature_level'] == "Warm"].groupby('sensor.altitude')

median_warm_air = warm_air.agg(median = ('voc','median'))

median_warm_air.sort_values(by = 'median', ascending = False).head(3)

                     median
sensor.altitude
3661             360.482708
3220             349.289333
1055             322.308333